### ISSUE TITLE
NFT Mall: invalid_redirect_uri

### ISSUE THREAD

**Issue by charliebrooksman** [unstoppabledomains/uauth#22]
error: "invalid_redirect_uri"
error description: "redirect_uri did not match any of the client's registered redirect_uris"

Partner would also like to know how to customize the theme of uauth modal. Partner also asked: "regarding the connector, we are using web3-react. can't we combine web3-react and uauth-web3 modal?"

We are hoping to feature NFT Mall in a twitter campaign on Tuesday (same with Akropolis and Tin.Network). Thank you!

**Comment by unstoppablelisa** [comment]
Most invalid_redirect_uri errors are caused by users not registering the Redirect Uris inside the configuration or not pasting that Uri correctly.

Redirect uris must match exactly with the the login server configuration.

They should go to their application page, change their redirect uri to http://localhost:4200, then click the get new credentials button.
